#!/usr/bin/env python3
"""Regenerate the vendored block/version index.

Pulls every post-flattening (1.13+) release registry from PrismarineJS
minecraft-data and collapses them into two files under
``src/minecraft_builder/data``:

* ``mc_versions.json``   — ordered releases with their NBT DataVersion
* ``block_versions.tsv`` — one row per block: added-in, removed-after

Run from the repo root::

    python scripts/regen_block_data.py

Versions Minecraft shipped under the year-based ``26.x`` scheme have no upstream
registry yet, so their blocks are held in PROVISIONAL below and sourced from
minecraft.wiki. Move an entry out of PROVISIONAL once minecraft-data catches up.
"""

from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

RAW = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data"
DATA_DIR = Path(__file__).resolve().parent.parent / "src" / "minecraft_builder" / "data"

# DataVersion of 1.13, the flattening — schematics predating it use numeric ids.
FLATTENING = 1519

RELEASE = re.compile(r"^\d+\.\d+(\.\d+)?$")

# Releases with no upstream block registry: {version: (DataVersion, [new blocks])}
PROVISIONAL: dict[str, tuple[int, list[str]]] = {
    "26.1": (4786, ["golden_dandelion"]),
    "26.1.1": (4788, []),
    "26.1.2": (4790, []),
    "26.2": (4903, [
        "chiseled_cinnabar", "cinnabar", "cinnabar_brick_slab",
        "cinnabar_brick_stairs", "cinnabar_brick_wall", "cinnabar_bricks",
        "cinnabar_slab", "cinnabar_stairs", "cinnabar_wall", "polished_cinnabar",
        "polished_cinnabar_slab", "polished_cinnabar_stairs",
        "polished_cinnabar_wall", "chiseled_sulfur", "polished_sulfur",
        "polished_sulfur_slab", "polished_sulfur_stairs", "polished_sulfur_wall",
        "potent_sulfur", "sulfur", "sulfur_brick_slab", "sulfur_brick_stairs",
        "sulfur_brick_wall", "sulfur_bricks", "sulfur_slab", "sulfur_spike",
        "sulfur_stairs", "sulfur_wall",
    ]),
}


def _fetch(url: str):
    with urllib.request.urlopen(url, timeout=60) as response:
        return json.load(response)


def main() -> None:
    paths = _fetch(f"{RAW}/dataPaths.json")["pc"]
    proto = _fetch(f"{RAW}/pc/common/protocolVersions.json")
    data_versions = {
        e["minecraftVersion"]: e["dataVersion"] for e in proto if e.get("dataVersion")
    }

    versions = sorted(
        (
            v for v in paths
            if "blocks" in paths[v]
            and RELEASE.match(v)
            and data_versions.get(v, 0) >= FLATTENING
        ),
        key=lambda v: data_versions[v],
    )
    print(f"{len(versions)} releases: {versions[0]} -> {versions[-1]}")

    cache: dict[str, set[str]] = {}
    registries: dict[str, set[str]] = {}
    for v in versions:
        path = paths[v]["blocks"]
        if path not in cache:
            cache[path] = {b["name"] for b in _fetch(f"{RAW}/{path}/blocks.json")}
            print(f"  fetched {path} ({len(cache[path])} blocks)")
        registries[v] = cache[path]

    rows: list[str] = []
    for block in sorted(set().union(*registries.values())):
        present = [v for v in versions if block in registries[v]]
        first, last = present[0], present[-1]
        span = versions[versions.index(first):versions.index(last) + 1]
        gaps = [v for v in span if block not in registries[v]]
        if gaps:  # a block that vanished and returned would break the span model
            raise SystemExit(f"{block} is non-contiguous, missing from {gaps}")
        rows.append(f"{block}\t{first}\t{'' if last == versions[-1] else last}")

    for version, (dv, blocks) in PROVISIONAL.items():
        versions.append(version)
        data_versions[version] = dv
        rows += [f"{b}\t{version}\t" for b in blocks]
    rows.sort()

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    (DATA_DIR / "block_versions.tsv").write_text(
        "# block<TAB>first_version<TAB>removed_after (blank = still present)\n"
        "# Generated by scripts/regen_block_data.py — do not edit by hand.\n"
        + "\n".join(rows) + "\n",
        encoding="utf-8",
    )
    (DATA_DIR / "mc_versions.json").write_text(
        json.dumps({
            "versions": versions,
            "data_versions": {v: data_versions[v] for v in versions},
            "provisional": list(PROVISIONAL),
            "note": (
                "Versions listed in 'provisional' have no upstream block registry "
                "(PrismarineJS stops at 1.21.11); their block lists come from "
                "minecraft.wiki and may be incomplete."
            ),
        }, indent=1) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {len(rows)} block rows across {len(versions)} versions")


if __name__ == "__main__":
    main()
